services:
  mcp_server:
    build: mcp_server/
    image: mcp_server
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    container_name: mcp_server

  simple_answer_system_api:
    build: simple_answer_system/
    image: simple_answer_system_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    container_name: simple_answer_system_api